apiVersion: v1
kind: Pod
metadata:
  name: mini-api-pod
  labels: 
    app: mini-api
spec:
  containers:
  - name: mini-api
    image: harbor.patras5g.eu/5gasp/mini-api-server:latest-x86
    ports:
      - name: http
        containerPort: 3001
        protocol: TCP
    command:
    - "/bin/sh"
    -  "-c"
    - "tail -f /dev/null"

